// Manifest is generated by `scripts/fetch-memes.mjs` from imgflip's public
// templates API. Re-run that script to refresh entries.
import manifest from "../data/memes.json";

export type Meme = {
  id: string;
  name: string;
  src: string;
  width: number;
  height: number;
  bytes: number;
};

export const memes: Meme[] = manifest as Meme[];

// Channel used by MemeGallery and MemePicker to hand a meme over to the Studio.
export const PICK_EVENT = "stegnokit:pick-carrier";

export async function memeToFile(meme: Meme): Promise<File> {
  const res = await fetch(meme.src);
  if (!res.ok) throw new Error(`failed to load meme (${res.status})`);
  const blob = await res.blob();
  const ext = meme.src.split(".").pop() || "jpg";
  return new File([blob], `${meme.id}.${ext}`, { type: blob.type || "image/jpeg" });
}

export async function pickMemeAsCarrier(meme: Meme): Promise<void> {
  const file = await memeToFile(meme);
  window.dispatchEvent(new CustomEvent<File>(PICK_EVENT, { detail: file }));
  document.getElementById("studio")?.scrollIntoView({ behavior: "smooth", block: "start" });
}
